[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"
  environment = { NODE_VERSION = "20.15.1", NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
